# Generated by Django 2.0.5 on 2019-11-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_all', '0002_auto_20191105_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='avatars/default.png', upload_to='avatars/', verbose_name='头像'),
        ),
    ]
